logging:
  level:
    com.spatacean.json.schema.podo.generator: trace

project:
  properties:
    name: @project.name@
    version: @project.version@
    description: @project.description@

server:
  forward-headers-strategy: native
